apiVersion: v1
kind: Service
metadata:
  name: "#{PROJECT_NAME}#-service"
  namespace: "ns-#{PROJECT_NAME}#-#{ENVIROMENT}#"
spec:
  type: LoadBalancer
  selector:
    app: "#{PROJECT_NAME}#"
  ports:
    - port: 8080
      targetPort: 8080
